[package]
name = "kardos"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "0.14.0", features = ["exts"] }
uefi-services = "0.11.0"
log = {version = "0.4", default-features = false}
